name: Deploy to GitHub Pages
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            pnpm-store-
        
      - name: Install dependencies
        run: pnpm --recursive install

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "::set-output name=gitCommitHash::$(git rev-parse HEAD)"

      - uses: actions/cache@v3
        id: docusaurus-build-cache
        with:
          path: |
            ./build
          key: docusaurus-build-pr-${{ github.event.number }}-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}
          restore-keys: |
            docusaurus-build-pr-${{ github.event.number }}-

      - name: Build docs
        run: |
          pnpm run build
        if: ${{ !steps.docusaurus-build-cache.outputs.cache-hit }}

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_branch: gh-pages
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
